server:
  port: 7070
  tomcat:
    max-connections: 1000
    accept-count: 100
    threads:
      max: 10
    access-log:
      enabled: true
    basedir: .logs/tomcat
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
spring:
  application:
    name: admin
  profiles:
    active: @profileActive@
  data:
    mongodb:
      uri: mongodb://172.16.2.141:27017/admin
      database: fobgochod
      authentication-database: admin
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 1GB
  cache:
    type: jcache
    jcache:
      config: classpath:/ehcache.xml
  output:
    ansi:
      enabled: ALWAYS
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      context-path: /admin
      client:
        url: http://localhost:7070/admin
        username: admin
        password: admin
        instance:
          service-base-url: http://localhost:7070
          metadata:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: ALWAYS
  info:
    env:
      enabled: true
logging:
  file:
    name: .logs/spring.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%21.21t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    console: ${logging.pattern.file}
info:
  version: @project.version@
  build-time: @timestamp@
  base-uri: http://localhost:7070
  wechat-uri: https://api.weixin.qq.com
