server:
  port: 31725
  tomcat:
    max-connections: 1000
    max-threads: 10
    accept-count: 100
  servlet:
    context-path: /api/dmc/v2
spring:
  application:
    name: admin
  profiles:
    active: @profileActive@
  data:
    mongodb:
      uri: mongodb://root:root@47.100.125.75:27017/admin
      database: fobgochod
      authentication-database: admin
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 1GB
  cache:
    type: jcache
    jcache:
      config: classpath:/ehcache.xml
app:
  base-uri: http://localhost:31725
  version: @project.version@
  build:
    time: @timestamp@