server:
  port: 7070
  tomcat:
    max-connections: 1000
    accept-count: 100
    threads:
      max: 10
    accesslog:
      enabled: true
    basedir: .logs/tomcat
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
spring:
  application:
    name: admin
  profiles:
    active: @profileActive@
  data:
    mongodb:
      uri: mongodb://172.16.2.141:27017/admin
      database: fobgochod
      authentication-database: admin
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 1GB
  cache:
    type: jcache
    jcache:
      config: classpath:/ehcache.xml
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - health
          - log
          - logfile
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always
    logfile:
      enabled: true
      external-file: logs/error
app:
  base-uri: http://localhost:7070
  version: @project.version@
  build-time: @timestamp@
  wechat-uri: https://api.weixin.qq.com
