server:
  port: 8080
  tomcat:
    max-connections: 1000
    accept-count: 100
    threads:
      max: 10
spring:
  application:
    name: admin
  profiles:
    active: @profileActive@
  data:
    mongodb:
      uri: mongodb://root:root@172.16.1.172:27017/admin
      database: fobgochod
      authentication-database: admin
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 1GB
  cache:
    type: jcache
    jcache:
      config: classpath:/ehcache.xml
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
        exclude: metrics
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always
    logfile:
      enabled: true
      external-file: logs/error
app:
  base-uri: http://localhost:8080
  version: @project.version@
  build-time: @timestamp@
  weixin:
    uri: https://api.weixin.qq.com
    app-id: wxf85af403aa802514
    app-secret: 1617f4bf0b3ed6e503b456fb05951c6c
